In [1]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a*2)
print(a*10)
print(a**2)

[ 2  4  6  8 10]
[10 20 30 40 50]
[ 1  4  9 16 25]


In [2]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print(a + b)

[11 22 33 44 55]


In [3]:
a = np.array([1, 2, 3])
b = np.array([1, 2])
print(a + b)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [4]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

print(a + b)

[[11 22 33]
 [14 25 36]]


In [24]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])  # (3,4)

b = np.array([1,2,3,4])   # (4,)
c = np.array([1,2,3])     # (3,)
d = np.array([1])          # (1,)

print(a + b)  
print(a + c)  
print(a + d)  

[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [6]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])  # (3,4)

b = np.array([1,2,3,4])   # (4,)
c = np.array([1,2,3])     # (3,)
d = np.array([1])          # (1,)

print(a + b)  # works?
print(a + d)  # works?

[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [7]:
a = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
              [[13,14,15,16],[17,18,19,20],[21,22,23,24]]])  # (2,3,4)

b = np.array([[10]])  # (1,1)
print(a + b)

[[[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]

 [[23 24 25 26]
  [27 28 29 30]
  [31 32 33 34]]]


In [10]:
a = np.array([[1,2,3],
              [4,5,6]])

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

21
[5 7 9]
[ 6 15]


In [16]:
a = np.array([[3,1,4],
              [1,5,9]])

print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.argmax(a))

9
1
3.8333333333333335
5


In [17]:
print(np.argmax(a, axis=0))
print(np.argmax(a, axis=1))

[0 1 1]
[2 2]


In [18]:
a = np.array([10, 20, 30, 40, 50])

print(a[0])
print(a[-1])
print(a[1:4])

10
50
[20 30 40]


In [19]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(b[0])      # first row
print(b[0][1])   # specific element
print(b[0, 1])   # same thing, cleaner syntax
print(b[:, 1])   # entire column

[1 2 3]
2
2
[2 5 8]


In [20]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(b[1:, 1:])

[[5 6]
 [8 9]]


In [21]:
a = np.array([10, 25, 30, 45, 50])
print(a[a > 30])

[45 50]


In [22]:
print(a > 30)

[False False False  True  True]


In [23]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(b[b > 4])

[5 6 7 8 9]
