In [1]:
import numpy as np

a = np.array([1,2,3,4,5,6])
print(a.shape)

b = a.reshape(2, 3)
print(b)
print(b.shape)

(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [2]:
a = np.array([1,2,3,4,5,6])
print(a.reshape(2,4))

ValueError: cannot reshape array of size 6 into shape (2,4)

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a.reshape(3, -1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a.reshape(3, -2))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a.reshape(2, -1))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [5]:
a = np.random.randint(0, 7, size=(1000, 64))
print(a.reshape(1000, 8, -1).shape)

(1000, 8, 8)


In [6]:
a = np.array([[1,2,3],
              [4,5,6]])

print("Original shape:", a.shape)
print(a)
print("\nTransposed shape:", a.T.shape)
print(a.T)

Original shape: (2, 3)
[[1 2 3]
 [4 5 6]]

Transposed shape: (3, 2)
[[1 4]
 [2 5]
 [3 6]]


In [28]:
print(np.zeros((3,3)))
print(np.ones((2,4)))
print(np.random.randint(0,  size=(3,3)))
print(np.random.random((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


ValueError: high <= 0

In [29]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a, b))

32


In [30]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

print(np.dot(a,b))

[[19 22]
 [43 50]]
