In [1]:
import numpy as np

a = np.array([10, 25, 30, 45, 50])
result = np.where(a > 30, 1, 0)
print(result)

[0 0 0 1 1]


In [2]:
a = np.array([10, 25, 30, 45, 50])
result = np.where(a > 30, a, 0)
print(result)

[ 0  0  0 45 50]


In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate([a, b]))

[1 2 3 4 5 6]


In [4]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[7,8,9],
              [10,11,12]])

print(np.concatenate([a, b], axis=0))
print(np.concatenate([a, b], axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.concatenate([a,b]))
print(np.stack([a,b]))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [6]:
a = np.ones((4,5))
b = np.ones((4,5))
c = np.ones((4,5))
print(np.stack([a,b,c]).shape)

(3, 4, 5)


In [7]:
a = np.array([[1,2],
              [3,4]])

print(np.linalg.det(a))
print(np.linalg.inv(a))
print(np.linalg.norm(a))

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
5.477225575051661
