Problem 1
Create a 5x5 array filled with random integers between 1 and 100. Then:
1. Find the maximum value and its position (row, column)
2. Replace all values greater than 50 with 0
3. Calculate the sum of each row

In [47]:
import numpy as np
a = np.random.randint(1,100,size = (5,5))
print(a)

[[21 48 41 31 26]
 [83 41 60 61 50]
 [41 37 83 50 97]
 [ 3 88 26  2 48]
 [30 62  4 99 59]]


###1. Find the maximum value and its position (row, column)

In [48]:
print("Max:", a.max(), "Position :",np.unravel_index(a.argmax(), a.shape))
print("Max Per Row : ", a.max(axis = 1), "Positions : ", a.argmax(axis = 1))
print("Max Per Column : ", a.max(axis = 0), "Positions : ", a.argmax(axis = 0))

Max: 99 Position : (np.int64(4), np.int64(3))
Max Per Row :  [48 83 97 88 99] Positions :  [1 0 4 1 3]
Max Per Column :  [83 88 83 99 97] Positions :  [1 3 2 4 2]


In [49]:
b = a.copy()
a[a > 50] = 0
print(a)

[[21 48 41 31 26]
 [ 0 41  0  0 50]
 [41 37  0 50  0]
 [ 3  0 26  2 48]
 [30  0  4  0  0]]


In [50]:
print("Sum of each row : ", a.sum(axis = 1))

Sum of each row :  [167  91 128  79  34]


In [51]:
flat_idx = a.argmax()
position = np.unravel_index(flat_idx, a.shape)
print(flat_idx)
print(position)

9
(np.int64(1), np.int64(4))


##Problem 2:
Create two 1D arrays of size 5 with random integers between 1-10. Then:

Calculate their dot product
Stack them vertically to form a 2x5 array
Transpose that array to get 5x2
Find the sum of each row in the transposed array

In [66]:
array1 = np.random.randint(1,10,size=(5))
array2 = np.random.randint(1,10,size=(5))
print(array1)
print(array2)

[5 5 6 5 7]
[8 8 2 2 7]


In [67]:
print("Dot Product : ",np.dot(array1,array2))

Dot Product :  151


In [90]:
array = np.stack([array1,array2])
print("Stack :",array)

Stack : [[5 5 6 5 7]
 [8 8 2 2 7]]


In [94]:
array = array.T
print( array )

[[5 8]
 [5 8]
 [6 2]
 [5 2]
 [7 7]]


In [101]:
print(np.sum(array,axis = 1))
print(array.sum(axis = 1))

[13 13  8  7 14]
[13 13  8  7 14]


Problem 3:
You have a chess board represented as an 8x8 array of zeros. Place:

Your pieces (value 1) on row 0 and row 1 (all squares)
Opponent pieces (value -1) on row 6 and row 7 (all squares)

Then:

Print the board
Use boolean indexing to count how many squares belong to you (value 1)
Use np.where to create a new array where your pieces become 100, opponent pieces become -100, empty stays 0

In [134]:
board = np.zeros([8,8])
print(board)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [135]:
board[:2,:] = 1
board[6:,:] = -1
print(board)

[[ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]]


In [128]:
print((board[board == 1]).shape[0])

16


In [136]:
board = np.where(board > 0,100,np.where(board == 0, 0, -100))
print(board)

[[ 100  100  100  100  100  100  100  100]
 [ 100  100  100  100  100  100  100  100]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [-100 -100 -100 -100 -100 -100 -100 -100]
 [-100 -100 -100 -100 -100 -100 -100 -100]]


Problem 4:
Create a 3x3 identity matrix (you've seen this concept — matrix with 1s on diagonal, 0s elsewhere). Then:

Verify that multiplying any 3x3 matrix by the identity matrix gives back the same matrix
Calculate the determinant of the identity matrix 
Create a 3x3 matrix of your choice and check if it's invertible 

In [143]:
matrix = np.identity(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [145]:
m = np.random.randint(1,101,size = (3,3))
print(m)

[[64 63  3]
 [17 49  8]
 [78  2 37]]


In [146]:
print(matrix @ m)

[[64. 63.  3.]
 [17. 49.  8.]
 [78.  2. 37.]]


In [155]:
print(np.linalg.det(matrix))

1.0


In [164]:
m = m/np.linalg.norm(m)
print(np.linalg.det(m))

0.04179071286312295


In [165]:
print(np.linalg.inv(m))

[[ 2.35165351 -3.04262349  0.46718993]
 [-0.00654328  2.79267033 -0.60329008]
 [-4.95718613  6.26322409  2.70237312]]


Problem 5:
You have 10 board positions, each 8x8, stored as a 3D array of shape (10, 8, 8) with random values 0-9.

Reshape it to (10, 64) — flatten each board into a single row
Find the sum of all values in board #3 (index 3)
Find which board (0-9) has the highest total sum — use a loop-free approach

In [166]:
board = np.random.randint(0,10,size = (10,8,8))
print(board)

[[[5 7 8 0 5 4 1 1]
  [2 0 8 2 5 9 5 8]
  [2 8 1 0 0 4 0 6]
  [9 7 0 2 7 3 5 1]
  [5 8 8 7 0 7 5 7]
  [5 4 6 9 9 7 2 9]
  [1 2 8 9 0 1 8 1]
  [3 0 0 7 5 4 8 6]]

 [[0 6 5 0 0 1 5 0]
  [8 6 7 5 8 1 0 3]
  [2 6 5 5 4 4 6 5]
  [0 8 1 7 4 2 8 8]
  [5 4 2 3 4 5 1 5]
  [4 4 7 2 5 2 1 3]
  [2 5 4 6 1 5 0 6]
  [4 5 9 3 8 6 9 5]]

 [[5 4 7 8 4 1 0 1]
  [5 3 6 1 9 6 3 1]
  [4 9 7 0 7 9 8 4]
  [0 3 3 3 6 8 3 6]
  [3 2 1 7 4 5 0 4]
  [9 2 2 7 4 9 0 6]
  [1 8 2 4 1 2 0 3]
  [5 0 8 1 0 0 0 2]]

 [[9 5 4 3 0 3 5 9]
  [4 1 9 7 9 8 9 7]
  [9 9 4 4 2 1 7 7]
  [5 4 9 4 6 2 6 5]
  [3 6 6 1 9 4 5 4]
  [3 4 8 2 3 2 9 3]
  [8 4 0 1 5 5 0 0]
  [6 0 4 2 0 4 1 2]]

 [[8 7 2 7 0 7 8 9]
  [0 6 1 7 0 1 0 3]
  [2 4 5 3 7 8 6 1]
  [4 5 4 8 9 7 7 2]
  [1 9 3 9 3 9 0 4]
  [0 9 9 0 8 5 0 6]
  [2 9 4 6 1 0 7 0]
  [1 4 4 8 2 6 6 5]]

 [[9 8 6 6 8 6 6 9]
  [1 8 4 3 8 1 6 0]
  [5 9 0 1 0 0 0 1]
  [3 3 8 2 3 7 0 5]
  [9 3 6 5 4 8 3 7]
  [5 2 3 8 0 1 3 3]
  [4 4 9 2 4 7 5 8]
  [8 5 4 9 8 2 1 3]]

 [[8 6 9 2 5 2 8 2]
  [0 0 7

In [171]:
new_board = board.reshape(10,64)
print(new_board)

[[5 7 8 0 5 4 1 1 2 0 8 2 5 9 5 8 2 8 1 0 0 4 0 6 9 7 0 2 7 3 5 1 5 8 8 7
  0 7 5 7 5 4 6 9 9 7 2 9 1 2 8 9 0 1 8 1 3 0 0 7 5 4 8 6]
 [0 6 5 0 0 1 5 0 8 6 7 5 8 1 0 3 2 6 5 5 4 4 6 5 0 8 1 7 4 2 8 8 5 4 2 3
  4 5 1 5 4 4 7 2 5 2 1 3 2 5 4 6 1 5 0 6 4 5 9 3 8 6 9 5]
 [5 4 7 8 4 1 0 1 5 3 6 1 9 6 3 1 4 9 7 0 7 9 8 4 0 3 3 3 6 8 3 6 3 2 1 7
  4 5 0 4 9 2 2 7 4 9 0 6 1 8 2 4 1 2 0 3 5 0 8 1 0 0 0 2]
 [9 5 4 3 0 3 5 9 4 1 9 7 9 8 9 7 9 9 4 4 2 1 7 7 5 4 9 4 6 2 6 5 3 6 6 1
  9 4 5 4 3 4 8 2 3 2 9 3 8 4 0 1 5 5 0 0 6 0 4 2 0 4 1 2]
 [8 7 2 7 0 7 8 9 0 6 1 7 0 1 0 3 2 4 5 3 7 8 6 1 4 5 4 8 9 7 7 2 1 9 3 9
  3 9 0 4 0 9 9 0 8 5 0 6 2 9 4 6 1 0 7 0 1 4 4 8 2 6 6 5]
 [9 8 6 6 8 6 6 9 1 8 4 3 8 1 6 0 5 9 0 1 0 0 0 1 3 3 8 2 3 7 0 5 9 3 6 5
  4 8 3 7 5 2 3 8 0 1 3 3 4 4 9 2 4 7 5 8 8 5 4 9 8 2 1 3]
 [8 6 9 2 5 2 8 2 0 0 7 8 7 3 1 6 6 7 4 2 5 2 8 9 4 6 5 5 6 3 6 2 4 6 2 2
  8 0 7 8 3 8 2 4 9 5 6 8 7 4 2 5 2 9 2 5 7 1 9 0 2 6 2 5]
 [3 6 7 0 9 5 2 9 8 3 4 4 1 2 3 8 5 3 8 9 2 4 2 0 2 0 0 5 9 5 4 3 8 7

In [172]:
print(new_board[3].sum())

290


In [177]:
print(np.argmax(new_board.sum(axis = 1)))

6
