In [1]:
import torch
import numpy as np

# NumPy array
a = np.array([1, 2, 3, 4, 5])

# PyTorch tensor
t = torch.tensor([1, 2, 3, 4, 5])

print(type(a))
print(type(t))
print(a)
print(t)

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
[1 2 3 4 5]
tensor([1, 2, 3, 4, 5])


In [4]:
# NumPy
a = np.array([2.0, 3.0, 4.0])
result_np = a ** 2
print("NumPy:", result_np)

# PyTorch
t = torch.tensor([2.0, 3.0, 4.0], requires_grad=True)
result_torch = t ** 2
result_torch.sum().backward()
print("PyTorch gradient:", t.grad)

NumPy: [ 4.  9. 16.]
PyTorch gradient: tensor([4., 6., 8.])


In [5]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print(a + b)
print(a * b)
print(torch.dot(a, b))
print(a.shape)
print(a.dtype)

tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor(32.)
torch.Size([3])
torch.float32


In [7]:
a = torch.tensor([1, 2, 3])      
b = torch.tensor([1.0, 2.0, 3.0]) 

print(a.dtype)
print(b.dtype)

torch.int64
torch.float32


In [15]:
import numpy as np
import torch

# NumPy → PyTorch
np_array = np.array([1.0, 2.0, 3.0])
tensor = torch.from_numpy(np_array)
print("From NumPy:", tensor)

# PyTorch → NumPy
back_to_numpy = tensor.numpy()
print("Back to NumPy:", back_to_numpy)

# Create tensor directly
zeros = torch.zeros(3, 4)
ones = torch.ones(2, 3)
random = torch.randn(3, 3)  # normal distribution, mean=0, std=1
print(zeros)
print(ones)
print(random.shape)

From NumPy: tensor([1., 2., 3.], dtype=torch.float64)
Back to NumPy: [1. 2. 3.]
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([3, 3])


In [16]:
A = torch.randn(3, 4)  # 3×4 matrix
B = torch.randn(4, 2)  # 4×2 matrix

# Two ways to do matrix multiplication
C1 = torch.mm(A, B)        # mm = matrix multiply
C2 = A @ B                  # same thing, cleaner syntax

print("Shape:", C1.shape)
print("Same result:", torch.allclose(C1, C2))

Shape: torch.Size([3, 2])
Same result: True


In [20]:
# Check if GPU available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Using device:", device)

# Move tensor to device
t = torch.randn(3, 3)
t = t.to(device)
print("Tensor device:", t.device)

Using device: cpu
Tensor device: cpu
